#!C:/Python/Python35/python.exe
print("Content-type:text/html\r\n\r\n")
print('<html>')
print('<head>')
print('<meta http-equiv = "Content-Type" content = "text/html; charset=iso-8859-9" / >')
print('<title>İlk Python Web Sayfam</title>')
print('</head>')
print('<body>')
print('<h2>Merhaba Dünya Bu Benim İlk Python Web Sayfam</h2>')
print('</body>')
print('</html>')